import Carousel from "../../components/Carousel"
import CarouselCards from "../../components/CarouselCards"

export default function Home() {



    return (
        <>
            <Carousel />
            {/* <ProductCard /> */}
            <CarouselCards />
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
            <h1>HOME</h1>
        </>
    )
}